import { LegendInfo } from './types';

export const LEGENDS: Record<string, LegendInfo> = {
  bangalore: { id: 'bangalore', displayName: 'Bangalore', class: 'Assault', tactical: 'Smoke Launcher', ultimate: 'Rolling Thunder', passive: 'Double Time', icon: 'https://api.mozambiquehe.re/assets/icons/legends/bangalore.png' },
  bloodhound: { id: 'bloodhound', displayName: 'Bloodhound', class: 'Recon', tactical: 'Eye of the Allfather', ultimate: 'Beast of the Hunt', passive: 'Tracker', icon: 'https://api.mozambiquehe.re/assets/icons/legends/bloodhound.png' },
  caustic: { id: 'caustic', displayName: 'Caustic', class: 'Controller', tactical: 'Nox Gas Trap', ultimate: 'Nox Gas Grenade', passive: 'Nox Vision', icon: 'https://api.mozambiquehe.re/assets/icons/legends/caustic.png' },
  crypto: { id: 'crypto', displayName: 'Crypto', class: 'Recon', tactical: 'Surveillance Drone', ultimate: 'Drone EMP', passive: 'Neurolink', icon: 'https://api.mozambiquehe.re/assets/icons/legends/crypto.png' },
  fuse: { id: 'fuse', displayName: 'Fuse', class: 'Assault', tactical: 'Knuckle Cluster', ultimate: 'The Motherlode', passive: 'Grenadier', icon: 'https://api.mozambiquehe.re/assets/icons/legends/fuse.png' },
  gibraltar: { id: 'gibraltar', displayName: 'Gibraltar', class: 'Support', tactical: 'Dome of Protection', ultimate: 'Defensive Bombardment', passive: 'Gun Shield', icon: 'https://api.mozambiquehe.re/assets/icons/legends/gibraltar.png' },
  horizon: { id: 'horizon', displayName: 'Horizon', class: 'Skirmisher', tactical: 'Gravity Lift', ultimate: 'Black Hole', passive: 'Spacewalk', icon: 'https://api.mozambiquehe.re/assets/icons/legends/horizon.png' },
  lifeline: { id: 'lifeline', displayName: 'Lifeline', class: 'Support', tactical: 'D.O.C. Heal Drone', ultimate: 'Care Package', passive: 'Combat Medic', icon: 'https://api.mozambiquehe.re/assets/icons/legends/lifeline.png' },
  loba: { id: 'loba', displayName: 'Loba', class: 'Support', tactical: 'Burglar\'s Best Friend', ultimate: 'Black Market Boutique', passive: 'Eye for Quality', icon: 'https://api.mozambiquehe.re/assets/icons/legends/loba.png' },
  mirage: { id: 'mirage', displayName: 'Mirage', class: 'Support', tactical: 'Psyche Out', ultimate: 'Life of the Party', passive: 'Now You See Me...', icon: 'https://api.mozambiquehe.re/assets/icons/legends/mirage.png' },
  newcastle: { id: 'newcastle', displayName: 'Newcastle', class: 'Support', tactical: 'Mobile Shield', ultimate: 'Castle Wall', passive: 'Retrieve the Wounded', icon: 'https://api.mozambiquehe.re/assets/icons/legends/newcastle.png' },
  octane: { id: 'octane', displayName: 'Octane', class: 'Skirmisher', tactical: 'Stim', ultimate: 'Launch Pad', passive: 'Swift Mend', icon: 'https://api.mozambiquehe.re/assets/icons/legends/octane.png' },
  pathfinder: { id: 'pathfinder', displayName: 'Pathfinder', class: 'Skirmisher', tactical: 'Grappling Hook', ultimate: 'Zipline Gun', passive: 'Insider Knowledge', icon: 'https://api.mozambiquehe.re/assets/icons/legends/pathfinder.png' },
  rampart: { id: 'rampart', displayName: 'Rampart', class: 'Controller', tactical: 'Amped Cover', ultimate: 'Sheila', passive: 'Modded Loader', icon: 'https://api.mozambiquehe.re/assets/icons/legends/rampart.png' },
  revenant: { id: 'revenant', displayName: 'Revenant', class: 'Assault', tactical: 'Shadow Pounce', ultimate: 'Forged Shadows', passive: 'Assassin\'s Instinct', icon: 'https://api.mozambiquehe.re/assets/icons/legends/revenant.png' },
  seer: { id: 'seer', displayName: 'Seer', class: 'Recon', tactical: 'Focus of Attention', ultimate: 'Exhibit', passive: 'Heart Seeker', icon: 'https://api.mozambiquehe.re/assets/icons/legends/seer.png' },
  valkyrie: { id: 'valkyrie', displayName: 'Valkyrie', class: 'Skirmisher', tactical: 'Missile Swarm', ultimate: 'Skyward Dive', passive: 'VTOL Jets', icon: 'https://api.mozambiquehe.re/assets/icons/legends/valkyrie.png' },
  vantage: { id: 'vantage', displayName: 'Vantage', class: 'Recon', tactical: 'Echo Relocation', ultimate: 'Sniper\'s Mark', passive: 'Spotter\'s Lens', icon: 'https://api.mozambiquehe.re/assets/icons/legends/vantage.png' },
  wattson: { id: 'wattson', displayName: 'Wattson', class: 'Controller', tactical: 'Perimeter Security', ultimate: 'Interception Pylon', passive: 'Spark of Genius', icon: 'https://api.mozambiquehe.re/assets/icons/legends/wattson.png' },
  wraith: { id: 'wraith', displayName: 'Wraith', class: 'Skirmisher', tactical: 'Into the Void', ultimate: 'Dimensional Rift', passive: 'Voices from the Void', icon: 'https://api.mozambiquehe.re/assets/icons/legends/wraith.png' },
  ash: { id: 'ash', displayName: 'Ash', class: 'Assault', tactical: 'Arc Snare', ultimate: 'Phase Breach', passive: 'Marked for Death', icon: 'https://api.mozambiquehe.re/assets/icons/legends/ash.png' },
  mad_maggie: { id: 'mad_maggie', displayName: 'Mad Maggie', class: 'Assault', tactical: 'Riot Drill', ultimate: 'Wrecking Ball', passive: 'Warlord\'s Ire', icon: 'https://api.mozambiquehe.re/assets/icons/legends/mad_maggie.png' },
  ballistic: { id: 'ballistic', displayName: 'Ballistic', class: 'Assault', tactical: 'Whistler', ultimate: 'Tempest', passive: 'Sling', icon: 'https://api.mozambiquehe.re/assets/icons/legends/ballistic.png' },
  catalyst: { id: 'catalyst', displayName: 'Catalyst', class: 'Controller', tactical: 'Piercing Spikes', ultimate: 'Dark Veil', passive: 'Barricade', icon: 'https://api.mozambiquehe.re/assets/icons/legends/catalyst.png' },
  conduit: { id: 'conduit', displayName: 'Conduit', class: 'Support', tactical: 'Radiant Transfer', ultimate: 'Energy Barricade', passive: 'Savior\'s Speed', icon: 'https://api.mozambiquehe.re/assets/icons/legends/conduit.png' },
  alter: { id: 'alter', displayName: 'Alter', class: 'Skirmisher', tactical: 'Void Passage', ultimate: 'Void Nexus', passive: 'Gift from the Rift', icon: 'https://api.mozambiquehe.re/assets/icons/legends/alter.png' },
};
