import { WeaponInfo } from './types';

export const WEAPON_MAP: Record<string, WeaponInfo> = {
  'r301': { display: 'R-301 Carbine', category: 'Assault Rifle', ammo: 'Light', icon: 'https://api.mozambiquehe.re/assets/icons/weapons/r301.png' },
  'flatline': { display: 'VK-47 Flatline', category: 'Assault Rifle', ammo: 'Heavy', icon: 'https://api.mozambiquehe.re/assets/icons/weapons/flatline.png' },
  'havoc': { display: 'HAVOC Rifle', category: 'Assault Rifle', ammo: 'Energy', icon: 'https://api.mozambiquehe.re/assets/icons/weapons/havoc.png' },
  'hemlok': { display: 'Hemlok Burst AR', category: 'Assault Rifle', ammo: 'Heavy', icon: 'https://api.mozambiquehe.re/assets/icons/weapons/hemlok.png' },
  'nemesis': { display: 'Nemesis Burst AR', category: 'Assault Rifle', ammo: 'Energy', icon: 'https://api.mozambiquehe.re/assets/icons/weapons/nemesis.png' },
  'alternator': { display: 'Alternator SMG', category: 'SMG', ammo: 'Light', icon: 'https://api.mozambiquehe.re/assets/icons/weapons/alternator.png' },
  'prowler': { display: 'Prowler Burst PDW', category: 'SMG', ammo: 'Heavy', icon: 'https://api.mozambiquehe.re/assets/icons/weapons/prowler.png' },
  'r99': { display: 'R-99 SMG', category: 'SMG', ammo: 'Light', icon: 'https://api.mozambiquehe.re/assets/icons/weapons/r99.png' },
  'volt': { display: 'Volt SMG', category: 'SMG', ammo: 'Energy', icon: 'https://api.mozambiquehe.re/assets/icons/weapons/volt.png' },
  'car': { display: 'C.A.R. SMG', category: 'SMG', ammo: 'Light/Heavy', icon: 'https://api.mozambiquehe.re/assets/icons/weapons/car.png' },
  'devotion': { display: 'Devotion LMG', category: 'LMG', ammo: 'Energy', icon: 'https://api.mozambiquehe.re/assets/icons/weapons/devotion.png' },
  'lstar': { display: 'L-STAR EMG', category: 'LMG', ammo: 'Energy', icon: 'https://api.mozambiquehe.re/assets/icons/weapons/lstar.png' },
  'spitfire': { display: 'M600 Spitfire', category: 'LMG', ammo: 'Light', icon: 'https://api.mozambiquehe.re/assets/icons/weapons/spitfire.png' },
  'rampage': { display: 'Rampage LMG', category: 'LMG', ammo: 'Heavy', icon: 'https://api.mozambiquehe.re/assets/icons/weapons/rampage.png' },
  'g7': { display: 'G7 Scout', category: 'Marksman', ammo: 'Light', icon: 'https://api.mozambiquehe.re/assets/icons/weapons/g7.png' },
  'triple_take': { display: 'Triple Take', category: 'Marksman', ammo: 'Energy', icon: 'https://api.mozambiquehe.re/assets/icons/weapons/triple_take.png' },
  '3030': { display: '30-30 Repeater', category: 'Marksman', ammo: 'Heavy', icon: 'https://api.mozambiquehe.re/assets/icons/weapons/3030.png' },
  'bocek': { display: 'Bocek Compound Bow', category: 'Marksman', ammo: 'Arrows', icon: 'https://api.mozambiquehe.re/assets/icons/weapons/bocek.png' },
  'charge_rifle': { display: 'Charge Rifle', category: 'Sniper', ammo: 'Sniper', icon: 'https://api.mozambiquehe.re/assets/icons/weapons/charge_rifle.png' },
  'longbow': { display: 'Longbow DMR', category: 'Sniper', ammo: 'Sniper', icon: 'https://api.mozambiquehe.re/assets/icons/weapons/longbow.png' },
  'kraber': { display: 'Kraber .50-Cal', category: 'Sniper', ammo: 'Unique', icon: 'https://api.mozambiquehe.re/assets/icons/weapons/kraber.png' },
  'sentinel': { display: 'Sentinel', category: 'Sniper', ammo: 'Sniper', icon: 'https://api.mozambiquehe.re/assets/icons/weapons/sentinel.png' },
  'eva8': { display: 'EVA-8 Auto', category: 'Shotgun', ammo: 'Shotgun', icon: 'https://api.mozambiquehe.re/assets/icons/weapons/eva8.png' },
  'mastiff': { display: 'Mastiff Shotgun', category: 'Shotgun', ammo: 'Shotgun', icon: 'https://api.mozambiquehe.re/assets/icons/weapons/mastiff.png' },
  'mozambique': { display: 'Mozambique Shotgun', category: 'Shotgun', ammo: 'Shotgun', icon: 'https://api.mozambiquehe.re/assets/icons/weapons/mozambique.png' },
  'peacekeeper': { display: 'Peacekeeper', category: 'Shotgun', ammo: 'Shotgun', icon: 'https://api.mozambiquehe.re/assets/icons/weapons/peacekeeper.png' },
  'p2020': { display: 'P2020', category: 'Pistol', ammo: 'Light', icon: 'https://api.mozambiquehe.re/assets/icons/weapons/p2020.png' },
  're45': { display: 'RE-45 Auto', category: 'Pistol', ammo: 'Light', icon: 'https://api.mozambiquehe.re/assets/icons/weapons/re45.png' },
  'wingman': { display: 'Wingman', category: 'Pistol', ammo: 'Sniper', icon: 'https://api.mozambiquehe.re/assets/icons/weapons/wingman.png' },
  'melee': { display: 'Melee', category: 'Melee', ammo: 'None', icon: 'https://api.mozambiquehe.re/assets/icons/weapons/melee.png' },
  'bleed_out': { display: 'Bleed Out', category: 'Environmental', ammo: 'None', icon: 'https://api.mozambiquehe.re/assets/icons/weapons/bleed_out.png' },
};
