import { WeaponInfo } from './types';

export const WEAPON_MAP: Record<string, WeaponInfo> = {
  'r301': { display: 'R-301 Carbine', category: 'Assault Rifle', ammo: 'Light' },
  'flatline': { display: 'VK-47 Flatline', category: 'Assault Rifle', ammo: 'Heavy' },
  'havoc': { display: 'HAVOC Rifle', category: 'Assault Rifle', ammo: 'Energy' },
  'hemlok': { display: 'Hemlok Burst AR', category: 'Assault Rifle', ammo: 'Heavy' },
  'nemesis': { display: 'Nemesis Burst AR', category: 'Assault Rifle', ammo: 'Energy' },
  'alternator': { display: 'Alternator SMG', category: 'SMG', ammo: 'Light' },
  'prowler': { display: 'Prowler Burst PDW', category: 'SMG', ammo: 'Heavy' },
  'r99': { display: 'R-99 SMG', category: 'SMG', ammo: 'Light' },
  'volt': { display: 'Volt SMG', category: 'SMG', ammo: 'Energy' },
  'car': { display: 'C.A.R. SMG', category: 'SMG', ammo: 'Light/Heavy' },
  'devotion': { display: 'Devotion LMG', category: 'LMG', ammo: 'Energy' },
  'lstar': { display: 'L-STAR EMG', category: 'LMG', ammo: 'Energy' },
  'spitfire': { display: 'M600 Spitfire', category: 'Light', ammo: 'Light' },
  'rampage': { display: 'Rampage LMG', category: 'Heavy', ammo: 'Heavy' },
  'g7': { display: 'G7 Scout', category: 'Marksman', ammo: 'Light' },
  'triple_take': { display: 'Triple Take', category: 'Marksman', ammo: 'Energy' },
  '3030': { display: '30-30 Repeater', category: 'Marksman', ammo: 'Heavy' },
  'bocek': { display: 'Bocek Compound Bow', category: 'Marksman', ammo: 'Arrows' },
  'charge_rifle': { display: 'Charge Rifle', category: 'Sniper', ammo: 'Sniper' },
  'longbow': { display: 'Longbow DMR', category: 'Sniper', ammo: 'Sniper' },
  'kraber': { display: 'Kraber .50-Cal', category: 'Sniper', ammo: 'Unique' },
  'sentinel': { display: 'Sentinel', category: 'Sniper', ammo: 'Sniper' },
  'eva8': { display: 'EVA-8 Auto', category: 'Shotgun', ammo: 'Shotgun' },
  'mastiff': { display: 'Mastiff Shotgun', category: 'Shotgun', ammo: 'Shotgun' },
  'mozambique': { display: 'Mozambique Shotgun', category: 'Shotgun', ammo: 'Shotgun' },
  'peacekeeper': { display: 'Peacekeeper', category: 'Shotgun', ammo: 'Shotgun' },
  'p2020': { display: 'P2020', category: 'Pistol', ammo: 'Light' },
  're45': { display: 'RE-45 Auto', category: 'Pistol', ammo: 'Light' },
  'wingman': { display: 'Wingman', category: 'Pistol', ammo: 'Sniper' },
  'melee': { display: 'Melee', category: 'Melee', ammo: 'None' },
};
